
config-version: 2
# Name your project!
name: 'my_new_project'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'fivetran'

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  my_new_project:
      # Applies to all files under models/example/
      example:
          materialized: table
